### PR TITLE
Added basic support for iTerm 2.9+ inline images

### PR DESCRIPTION
**Pull request by seanson**
This commit allows users of iTerm 2.9+ (currently in Beta) to have images displayed natively in their terminal. I have added a new optional configuration item to enable the behaviour: `IMAGE_ON_ITERM`, which will enable it for both timeline images and profile images. Additionally, the existing `IMAGE_MAX_HEIGHT` is used to limit height.

As a bonus, iTerm allows you to Command-Click an inline image and it will be displayed natively in Preview.

iTerm support has also been requested as part of #135 but as far as I know only OSX's iTerm2 has implemented the escape sequence.

### CODE REVIEW

**Comment by seanson** [comment]
Is this project still active?

**Comment by NicholasDunham** [comment]
@seanson I was wondering the same. I saw your pull request and cloned your fork of Rainbowstream, but so far I haven't managed to make it work. I set IMAGE_ON_ITERM to True, logged in successfully, but images aren't showing up in the terminal. Not sure what I'm missing.

I had hoped that this feature would be in Rainbowstream by now, since iTerm2 has had support for inline images for a while now, but as you've noted, this project doesn't seem to be actively maintained anymore.

**Comment by NicholasDunham** [comment]
@seanson I figured out why your version wasn't displaying images inline on my system: I'm running Rainbowstream inside tmux. I did a little hacking at it, and did get it to display images (using [imgcat](https://raw.githubusercontent.com/gnachman/iTerm2/master/tests/imgcat) as an example), but there are still some pretty big limitations. One is that when the cursor moves or the screen scrolls, the images aren't aware of the change. Another is that when you have multiple panes, the images display wherever the active cursor is, which isn't necessarily in the pane Rainbowstream is running in.

These are limitations in tmux, not in Rainbowstream or iTerm2. Until someone finds a way around these issues, I can live without inline images in Rainbowstream—tmux is more important to me right now. Good work on the fork, though!

**Comment by seanson** [comment]
@NicholasDunham I believe it would require some sort of collaboration between iTerm2 and tux unfortunately.

**Comment by snobu** [comment]
+1 for this. Turns rainbowstream into a whole new application.
image

**Comment by joech4n** [comment]
+1

**Pull request closed without merging**
