### PR TITLE
SIXEL support.

### PR DESCRIPTION
**Pull request by peterjschroeder**
Support for real images using SIXEL.
In rainbow_config.json change "IMAGE_ON_TERM" : true to "sixel".
Tested in MLTerm on 2 machines running Debian Sid with different screen sizes. Works correctly.

### CODE REVIEW

**Comment by orakaro** [comment]
Thank you for your effort 👍. Could you provide a testing guidance? I am using a Mac and completely have no idea about SIXEL 🙇‍♂️

**Comment by peterjschroeder** [comment]
I don't have a mac to test it on, but it looks like iterm2 supports it.

**Comment by Nithilher** [comment]
> I don't have a mac to test it on, but it looks like iterm2 supports it.

I tried your patch. Rainbowstream starts successfully, but says "Sorry, image link is broken" instead of showing the images rendered by sixel.

**Comment by danger89** [comment]
Please merge

**Comment by orakaro** [comment]
I can't run this PR on my Mac. Changing `IMAGE_ON_TERM ` to sixel results in `Sorry, image link is broken`

**Comment by danger89** [comment]
> 

I give give the same answer you gave to somebody else in 2014. Maybe it solves your issue:

```
sudo apt-get install libjpeg-dev
pip install -I PIL  # inside virtualenv
rainbowstream -iot
```

Otherwise print the full error log, in order to see what the root cause may be. I now can only guess its maybe related to https://github.com/orakaro/rainbowstream/issues/41#issuecomment-52857511

**Comment by slarrain** [comment]
> I can't run this PR on my Mac. Changing `IMAGE_ON_TERM ` to sixel results in `Sorry, image link is broken`

I ran into the same issue. For me what fixed it was one of this 2 (can't remember which one, or maybe both):
```sh
sudo apt install libsixel-bin
sudo pip3 install libsixel-python
```

Let us know if that works for you.

Just FYI, I got this patch to work and looks great (my terminal is [Wezterm](https://wezfurlong.org/wezterm/)):

image

**Comment by peterjschroeder** [comment]
libsixel-python is the dependency.

**Comment by slarrain** [comment]
By the way, the [Kitty Terminal Emulator](https://sw.kovidgoyal.net/kitty) doesn't support `sixel`. However, it does support its own _Image on the terminal_ implementation. I started playing around and actually got it work (at least on Kitty and on Linux).
I think it could be interesting to add support for rendering Image previews on Kitty terminals to `rainbowstream`.

**Comment by danger89** [comment]
> Kitty

This is a really specific terminal. I never hear about this GPU accelerated terminal emulator. Nice. I currently just use the default `xfce4-terminal` with bash and [Starship Prompt](https://starship.rs/). I expect no issues here with SIXEL.

**Comment by orakaro** [comment]
Thank everyone for jumping in. Here is my test so far: (Mac Big Sur 11.0.1 / Iterm2 3.5+)

* `brew install libsixel`
* Checkout and install this branch, confirm libsixel-python is installed
* Run `home` and can't see anything
* I doubt that sixel doesn't work on my system at all. Running `img2sixel` against a simple png file doesn't display anything

**Comment by slarrain** [comment]
That is strange, Supposedly, `iTerm2 3.0+` is [compatible](https://github.com/saitoha/libsixel#terminal-requirements) with `sixel`.
Perhaps you could try with [wezterm](https://github.com/wez/wezterm), just to make sure that is not a terminal thing.

> Run home and can't see anything

You mean nothing at all or no images? Did you change your config to `sixel`? If you change it back to `True`, does it display the ASCII images? 
Have you been able to debug it at all? For example, on the `c_image.py` file, is it going inside the `sixel` `if` statement?

**Comment by orakaro** [comment]
Yes, I believe my Iterm version is higher than required.

> Perhaps you could try with wezterm,

Will do, thanks.

> You mean nothing at all or no images? Did you change your config to sixel? If you change it back to True, does it display the ASCII images?

I see normal tweets, just no images. I changed and confirmed my IMAGE_ON_TERM is sixel. If I change back to True, I can see the ASCII images again.

> Have you been able to debug it at all? For example, on the c_image.py file, is it going inside the sixel if statement?

Yes it does. Debugging shows that `sixel.getvalue()` has value, however `sixel.getvalue().decode('ascii')` is blank

**Comment by orakaro** [comment]
Hello, @slarrain wezterm worked absolutely well. Awesome
sixel

Huge thanks to @peterjschroeder for your efforts and everyone for pushing this. I will make this available on PyPi soon

**Pull request merged**
